### ISSUE TITLE
Hier heb je geen loopje nodig

### ISSUE THREAD

**Issue by vasilisvg** [rianneeh/Frontend-for-designers#1]
Dit kan makkelijker. Als ik het goed begrijp wil je hier de class `show` weghalen. En als ik het goed begrijp dan komt die klas altijd maar één keer voor in de hele HTML, toch? In dat geval kan je ook gewoon dit doen:

```css
document.querySelector('.show).classList.remove('show');
```

En dat geldt natuurlijk ook voor de loop daaronder. Dat maakt het nét iets makkelijker.

https://github.com/rianneeh/Frontend-for-designers/blob/8f1d7e1955cabeb8edbf82af698c3093d9644d4e/opdracht2/v1/js/script.js#L30

**Comment by rianneeh** [comment]
Opgelost door class="active" in html aan de eerste dot toe te voegen en de gegeven code te gebruiken!
